# external-secrets Base Values
# Fork: MisterGrinvalds/external-secrets.external-secrets
# Chart: deploy/charts/external-secrets

# Install CRDs
installCRDs: true

# Webhook configuration
webhook:
  create: true

# Cert controller
certController:
  create: true

# Resources
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
